// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: create_person.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreatePersonParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.ID, arg.Name)
	var i Person
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
