// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: delete_person.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePerson = `-- name: DeletePerson :one
DELETE FROM persons
WHERE id=$1
RETURNING id, name
`

func (q *Queries) DeletePerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, deletePerson, id)
	var i Person
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
