// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: fetch_person.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const fetchPerson = `-- name: FetchPerson :one
SELECT id, name FROM persons WHERE id=$1
`

func (q *Queries) FetchPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, fetchPerson, id)
	var i Person
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
