// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: update_person.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET name = $1
WHERE id = $2
RETURNING id, name
`

type UpdatePersonParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson, arg.Name, arg.ID)
	var i Person
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
